---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: '3-jdk-8'

inputs:
- name: source-code

outputs:
- name: build-output
  path: build-output

run:
  path: source-code/ci/Scripts/build.sh