---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: '3-jdk-8'

inputs:
- name: source-code

outputs:
- name: build-output
  path: build-output

run:
  path: mvn
  args: ["-f", "source-code/pom.xml", "install" , "-Ddir=/build-output"]