---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: '3-jdk-8'

inputs:
- name: source-code

#outputs:
#- name: build-output
#  path: source-code/target

run:
  path: mvn
  args: ["-f", "-e", "source-code/pom.xml", "package"]