---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: '3-jdk-8'

inputs:
- name: build-output

outputs:
- name: moved-file
  path: moved-file

run:
  path: mv
  args: ["build-output/target/*.jar","moved-file/."]