
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: patrickcrocker/cloudfoundry-cli
    tag: 'latest'

inputs:
- name: pipeline
- name: release

outputs:
- name: prepare-manifest-output

params:
  CF_ARTIFACT_ID:
  CF_APP_NAME:
  CF_APP_HOST:
  CF_APP_SERVICES:
  DB_HOST:
  DB_PORT:
  DB_USER:
  DB_PASSWORD:
  DB_NAME:
  LDAP_URI:

run:
  path: pipeline/ci/scripts/prepare-manifest.sh