---
resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/cah-jeremykuhn/springboot-sample-pcf.git
      branch: master
  - name: deploy-pcf
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-organization}}
      space: {{cf-space}}
      skip_cert_check: true

jobs:
- name: build-and-deploy
  plan:
  - aggregate:
    - get: source-code
      trigger: true
  - task: build
    file: source-code/ci/Tasks/build.yml
  - put: deploy-pcf
    params:
      manifest: source-code/manifest.yml
      path: build-output/samplepcfdeploy-0.0.1-SNAPSHOT.jar