---
resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/cah-jeremykuhn/springboot-sample-pcf.git
      branch: master

jobs:

- name: build-maven
  plan:
  - aggregate:
    - get: source-code
      trigger: true
  - task: build
    file: source-code/ci/Tasks/build.yml
  - task: movefile
    file: source-code/ci/Tasks/movefile.yml