---
resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/cah-jeremykuhn/springboot-sample-pcf.git
      branch: master
  - name: deploy-pcf
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-organization}}
      space: {{cf-space}}
      skip_cert_check: true

jobs:
- name: build-maven
  plan:
  - aggregate:
    - get: source-code
      trigger: true
  - task: build
    file: source-code/ci/Tasks/build.yml
- name: deploy
  plan: 
  - aggregate:
    - get: build-maven
      passed: [ build-maven ]
      trigger: true
    - put: deploy-pcf
      params: 
        manifest: source-code/manifest.yml
        path: source-code